Python 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import boto3
... 
... ec2 = boto3.client('ec2')
... 
... def start_instance(instance_id):
...     response = ec2.start_instances(InstanceIds=[instance_id])
...     print(f"Starting instance {instance_id}: {response}")
... 
... def stop_instance(instance_id):
...     response = ec2.stop_instances(InstanceIds=[instance_id])
...     print(f"Stopping instance {instance_id}: {response}")
... 
... instance_id = 'i-0abcd1234efgh5678'
... start_instance(instance_id)
... # To stop: stop_instance(instance_id)
... 
... 
... 
