Python 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import subprocess
... 
... def uninstall_software(software_name):
...     try:
...         command = f'powershell "Get-WmiObject -Class Win32_Product | Where-Object {{ $_.Name -like \'{software_name}*\' }} | ForEach-Object {{ $_.Uninstall() }}"'
...         subprocess.run(command, shell=True, check=True)
...         print(f"Software {software_name} uninstalled successfully.")
...     except subprocess.CalledProcessError as e:
...         print(f"Error uninstalling software: {e}")
... 
... uninstall_software('ExampleSoftware')
... 
... 
... 
... 
