Python 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import requests
... 
... def download_file(url, local_filename):
...     with requests.get(url, stream=True) as r:
...         r.raise_for_status()
...         with open(local_filename, 'wb') as f:
...             for chunk in r.iter_content(chunk_size=8192):
...                 f.write(chunk)
...     print(f"Downloaded {local_filename}")
... 
... if __name__ == "__main__":
...     download_file("https://example.com/file.txt", "downloaded_file.txt")
... 
... 
... 
... 
... 
... 
