Python 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import os
... import psutil
... 
... def check_cpu_usage(threshold):
...     usage = psutil.cpu_percent(interval=1)
...     return usage > threshold
... 
... def reboot_system():
...     os.system('sudo reboot')
... 
... if check_cpu_usage(90):
...     print("CPU usage is high. Rebooting system...")
...     reboot_system()
... else:
...     print("CPU usage is within acceptable limits.")
... 
... 
... 
... 
