Python 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import schedule
... import time
... 
... def job():
...     print("Scheduled task running...")
... 
... schedule.every().day.at("10:00").do(job)
... 
... while True:
...     schedule.run_pending()
...     time.sleep(1)
... 
... 
... 
