Python 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import os
... 
... def schedule_shutdown(minutes):
...     try:
...         os.system(f'shutdown -s -t {minutes * 60}')
...         print(f"System will shut down in {minutes} minutes.")
...     except Exception as e:
...         print(f"Error scheduling shutdown: {e}")
... 
... shutdown_minutes = 30
... schedule_shutdown(shutdown_minutes)
... 
... 
... 
