Python 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> from azure.identity import DefaultAzureCredential
... from azure.mgmt.resource import ResourceManagementClient
... 
... subscription_id = 'your_subscription_id'
... resource_group = 'your_resource_group'
... 
... credential = DefaultAzureCredential()
... resource_client = ResourceManagementClient(credential, subscription_id)
... 
... async_delete = resource_client.resource_groups.begin_delete(resource_group)
... async_delete.result()
... print(f"Resource group {resource_group} deleted successfully.")
... 
... 
... 
... 
