Python 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> from azure.identity import DefaultAzureCredential
... from azure.mgmt.compute import ComputeManagementClient
... 
... subscription_id = 'your_subscription_id'
... credential = DefaultAzureCredential()
... compute_client = ComputeManagementClient(credential, subscription_id)
... 
... vm_list = compute_client.virtual_machines.list_all()
... for vm in vm_list:
...     print(f"VM Name: {vm.name}, Location: {vm.location}")
... 
... 
... 
